server:
  port: 8082

spring:
  application:
    name: finance-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/finance_db}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  openrouter:
    api-key: ${OPENROUTER_API_KEY}
    model: ${OPENROUTER_MODEL:gpt-oss-120b:free}
