server:
  port: 8082

spring:
  application:
    name: finance-service
  data:
    mongodb:
      uri: ${FINANCE_MONGODB_URI:mongodb://localhost:27017/finance_db}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  groq:
    api-key: ${GROQ_API_KEY}
    model-realtime: ${GROQ_MODEL_REALTIME:llama-3.1-8b-instant}
    model-analytics: ${GROQ_MODEL_ANALYTICS:llama-3.3-70b-versatile}
